spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raven
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    title: API Calculadora
    description: Documentación de endpoints de usuarios
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "PsjOdFFvBWrbxTrFZouAJyVZ3rZ+/arAfZ8lllsEWF4Xf8KPxK90aji3BCTfCgLAUMLdjxpfELsA9VUu04aJEw=="
  expiration: 3600000